# Speed up latexmk-xelatex compilation re pdfx
$hash_calc_ignore_pattern{'timestamp'} = '^';

# Output PDF to output/ folder
$out_dir = 'output';

# Keep auxiliary files in auxfiles/ folder (aux is a reserved Windows name)
$aux_dir = 'auxfiles';
